# Generated by Django 2.0.1 on 2018-11-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='pid_list',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='父权限列表'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='访问url地址'),
        ),
    ]
