# Generated by Django 2.0.1 on 2018-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181127_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='pid_list',
        ),
        migrations.AddField(
            model_name='permission',
            name='per_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='权限级别'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='访问url地址'),
        ),
    ]
