# Generated by Django 2.0.1 on 2018-11-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20181128_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pids',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='父权限组合'),
        ),
    ]
