# Generated by Django 2.0.1 on 2018-11-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_permission_pids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='per_level',
        ),
    ]
