# Generated by Django 2.1.1 on 2019-08-14 05:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190813_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuses',
            options={'verbose_name': '校区表', 'verbose_name_plural': '校区表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级表', 'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户表', 'verbose_name_plural': '客户表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, null=True, to='app1.ClassList', verbose_name='已报班级'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LinuxL', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发')], max_length=22, null=True, verbose_name='咨询课程'),
        ),
    ]
