# Generated by Django 2.1.1 on 2019-09-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_remove_permission_per_level'),
        ('app1', '0006_auto_20190903_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='用户所拥有的角色'),
        ),
    ]
